Closes #1606 - Change "Url" text to "URL"
gitkraken/vscode-gitlens pull request #1771
Opened 2022-01-16 12:15 UTC by pguilbert

---
#1606

# Description

Change all occurrence of the capitallized "Url" to "URL" to match with the [Visual Studio Code Language Packs](https://github.com/microsoft/vscode-loc).

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

2022-01-16 12:28 UTC, pguilbert commented
... I don't know how I missed the previous PR #1607. 

Is this issue still relevant ?

2022-02-17 20:05 UTC, JamieEdge commented
I agree that the issue is still relevant. URL is an acronym and should be capitalised. The current capitalisation was noticeable to me and led me to find this pull request and its related issue.

Under certain symbol naming conventions it is not unusual to see only the first letter of the acronym capitalised on occasion to improve readability (e.g. `repositoryUrlLength`), but in a user interface this is not correct.

The [Oxford English Dictionary](https://www.oed.com/view/Entry/258858), [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/url) and [Merriam-Webster Dictionary](https://www.merriam-webster.com/dictionary/URL) all define URL as a fully capitalised acronym and use it as such in their examples.

2022-03-25 00:07 UTC, seahyinghang8 commented on src/commands/openBranchesOnRemote.ts
>  		if (!repoPath) return;
what is this

2022-06-14 21:44 UTC, dnicolson commented
Thank you for your comment @JamieEdge and your contribution @pguilbert, I believe this issue is still relevant. It's unfortunate that https://github.com/gitkraken/vscode-gitlens/pull/1607 was closed.

2022-11-03 04:20 UTC, eamodio commented
Thanks! I've come around and am open to merging this once the conflicts are resolved and the other missing instances are included.

2022-11-03 04:20 UTC, eamodio requested changes
See main comment

2022-11-06 18:42 UTC, dnicolson commented
@pguilbert are you able take a look at this?

2022-11-11 18:47 UTC, dnicolson commented
@eamodio please have a look at https://github.com/gitkraken/vscode-gitlens/pull/2341.

2022-11-12 07:45 UTC, closed without merging