Fixes #1805 to prevent tracking remote branches if the local branch has not the same name
gitkraken/vscode-gitlens pull request #1817
Opened 2022-02-10 16:58 UTC by qadram

# Description

When creating a branch, if the ref is remote, then passes along the --no-track option to be added to the command line, both for the branch command, or for the checkout -b command.

2022-04-13 05:02 UTC, eamodio commented on src/commands/git/branch.ts
> +			if ((state.reference as GitBranchReference).remote) {
Here we need to do a check that we are dealing with a branch (because the `reference` could be a commit or tag or something else.

2022-04-13 05:05 UTC, eamodio commented on src/commands/git/switch.ts
> +						r.switch(state.reference.ref, { createBranch: state.createBranch, progress: false, track: false }),
Is this an intentional change in behavior? Because `switch` will now always add the `--no-track` flag, which I'm not sure is desired.

2022-04-13 05:06 UTC, eamodio requested changes
@qadram sorry for the delay on this -- added some comments and can you rebase this?

2024-07-18 20:31 UTC, WarDroid23 reviewed
.

2026-09-14 21:04 UTC, d13 commented
Resolved with a88f80ef05ce5d62166a72b28af0f59003c0d47d

2026-09-14 21:04 UTC, closed without merging