Graph: Use default column widths
gitkraken/vscode-gitlens pull request #2137
Opened 2022-08-08 15:23 UTC by miggy-e

Right now, when users first open their graph, they end up using the minimum column widths since the component sends over widths of 0. In this PR, I set up a default column width size that'll adequately show more information in the graph than the minimum (by default the graph nodes are squashed into a single column).

Future work includes auto-sizing the columns, but seems like this is a good fix for now.

testing:
In order to clear your current storage, you can add this line
`void this.container.storage.deleteWorkspace(WorkspaceStorageKeys.GraphColumns);` to the getConfig function in graphWebview.ts and opened the graph.

2022-08-08 17:23 UTC, axosoft-ramint approved these changes

2022-08-08 17:35 UTC, ericf-axosoft requested changes

2022-08-08 17:35 UTC, ericf-axosoft commented on src/webviews/apps/plus/graph/GraphWrapper.tsx
> +	};
```suggestion
const getGraphColSettingsModel = (config?: GraphConfig): GKGraphColumnsSettings => {
  const columnsSettings: GKGraphColumnsSettings = {};
  if (config?.columns !== undefined) {
    for (const key of Object.keys(config.columns)) {
      columnsSettings[key] = {
	width: config.columns[key].width || defaultGraphColumnsSettings[key],
      };
  }
}
return columnsSettings;
```

2022-08-08 17:46 UTC, ericf-axosoft approved these changes

2022-08-08 18:13 UTC, ericf-axosoft requested changes

2022-08-08 18:13 UTC, ericf-axosoft commented on src/webviews/apps/plus/graph/GraphWrapper.tsx
> +			const width = config.columns[key].width;
```suggestion
const getGraphColSettingsModel = (config?: GraphConfig): GKGraphColumnsSettings => {
	const columnsSettings: GKGraphColumnsSettings = { ...defaultGraphColumnsSettings };
	if (config?.columns !== undefined) {
		for (const column of Object.keys(config.columns)) {
			columnsSettings[column] = {
				width: config.columns[column].width,
			};
		}
	}
	return columnsSettings;
};
```

2022-08-10 09:19 UTC, ericf-axosoft approved these changes

2022-08-10 09:20 UTC, merged