Fixes #2836 adds sorting by repositories
gitkraken/vscode-gitlens pull request #2991
Opened 2023-10-31 05:25 UTC by aidoskanapyanov

# Description
Adds an option to sort repositories in repositories view via name (asc/desc), last fetched (asc/desc), starred. Solves #2836 

# Demo
https://github.com/gitkraken/vscode-gitlens/assets/65722512/dfbe455b-bfbf-48cc-bb0e-01ceff0c1777

# Checklist
- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [ ] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

2023-10-31 06:07 UTC, eamodio requested changes
Thanks for this! Looks great, though I'd rather have "starred" repos always affect the sorting (like we do with branches).

2023-10-31 06:07 UTC, eamodio commented on package.json
> +						"starredFirst": "lastFetched:desc",
`"starredFirst"` should be `"default"`

2023-10-31 06:07 UTC, eamodio commented on package.json
> +							"starredFirst"
Let's nuke "starredFirst" and just always have starred as the first order of sorting (similar to branches)

2023-10-31 06:07 UTC, eamodio commented on src/git/models/repository.ts
> +	current?: true;
`current` can just be nuked

2023-10-31 06:45 UTC, aidoskanapyanov commented
Hi @eamodio , thank you for the review! 👋
I addressed the comments in 8f022d4

2023-10-31 18:56 UTC, merged

2023-10-31 18:57 UTC, eamodio commented
Thank you so much for your contribution!

![Thank you!](https://media.giphy.com/media/tIeCLkB8geYtW/giphy.gif)

2023-10-31 19:01 UTC, eamodio commented
FYI, I moved all the "sort" settings to a new "Sorting" section in the UI (ours and vscode's). And I added an option for the current behavior called "discovered" and made that the default to not change things for existing users. Also note that the `lastFetched:*` options have some performance overhead to enabling them since we have to do more work to keep that date up to date and have to refresh more of the views to re-sort.

2023-11-01 04:28 UTC, aidoskanapyanov commented
Thanks @eamodio!👋
It's always nice to learn new things :)