feat: add banner to welcome page
gitkraken/vscode-gitlens pull request #3241
Opened 2024-04-22 04:27 UTC by cmgriffing

## ❤ Thank you for contributing to GitLens! ❤

### 🚨 IMPORTANT 🚨

I neglected this issue because I think we recognize the value for the PR from messages in an internal Slack context.

Narrow view:
![_Extension_Development_Host__Welcome_to_GitLens_—_Debugging__GitLens_](https://github.com/gitkraken/vscode-gitlens/assets/1195435/895beb71-ce87-4da8-8de7-5c54da26cfbe)

Desktop view:
![_Extension_Development_Host__Welcome_to_GitLens_—_Debugging__GitLens_](https://github.com/gitkraken/vscode-gitlens/assets/1195435/c1090eb1-3cb8-498f-84f8-759f9ffc9081)

There might be other views that aren't perfect but I think this fills the void that we need for now. I am happy to change anything as needed.

2024-04-22 04:36 UTC, cmgriffing commented
Hey all, I just added this without an issue, but I think it does what we need from a marketing standpoint. I am happy to make any changes as needed.

2024-04-22 05:22 UTC, d13 requested changes
- Some changes to the HTML & CSS.
- Did you test this against multiple themes, especially light themes in this case, for color contrast?
- We'll need to hide the banner after the registration date and/or the event ends. We want to avoid a patch release to do that, so controlling that with some JS on `welcome.ts` will work.
- Our commit messages use a future-tense format (`Adds`, `Updates`, `Fixes`, etc): 
    > Adds workshop banner to welcome page

2024-04-22 05:22 UTC, d13 commented on src/webviews/apps/welcome/welcome.scss
> +			}
Should be able to just use custom properties with `<gl-button>`.
 
```
  --button-foreground: white;
  --button-background: #c64eff;
```

2024-04-22 19:11 UTC, cmgriffing commented on src/webviews/apps/welcome/welcome.scss
> +			}
Since they are spans, text-align puts them on the same line. By doing a flex column, we force them onto new lines.

2024-04-22 19:19 UTC, d13 commented on src/webviews/apps/welcome/welcome.scss
> +			}
True, the flexbox is fine. You could also make the spans `display: block;` too.

2024-04-24 07:29 UTC, anilu258 commented
[Uploading 3241.patch…]()
[auto-merge.yml.txt](https://github.com/gitkraken/vscode-gitlens/files/15090399/auto-merge.yml.txt)

2024-04-24 19:48 UTC, d13 commented
Resolved with https://github.com/gitkraken/vscode-gitlens/tree/v14.9.1

2024-04-24 19:48 UTC, closed without merging