Fix `GitCodeLensProvider.resolveGitAuthors…` "others" pluralization.
gitkraken/vscode-gitlens pull request #3296
Opened 2024-05-15 21:49 UTC by bm-w

# Description

Fixes Authors lens to say e.g. “one other” (in full “2 authors (Jane Doe and one other)”) when there are 2 authors (#3295).

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

2024-05-15 21:55 UTC, NinoScript approved these changes

2024-05-16 02:04 UTC, TJohnsonSE requested changes
This looks this change has a bug where the generated 'andOthers' string is squished against the 'author' trunk.  See screenshot below:

![image](https://github.com/gitkraken/vscode-gitlens/assets/79184128/cc907620-cc74-443b-aad1-0336127b0f96)

My recommendation is to just change the ternary evaluation to check for "count > 2", since the only time you'll generate "and one other" is when count is exactly 2.

Something like this should work:

let title = `${pluralize('author', count, { zero: '?' })} (${author}${
			count > 2 ? ' and others' : ' and 1 other'
		})`;

2024-05-16 12:08 UTC, bm-w commented
Oops, @TJohnsonSE, thanks for catching the squishing — fixed!

2024-05-31 14:45 UTC, d13 approved these changes

2024-05-31 14:54 UTC, merged

2024-05-31 15:49 UTC, d13 commented
@bm-w thank you for the contribution!

![Thank you](https://github.com/gitkraken/vscode-gitlens/assets/293282/efb8a1e9-94e4-422c-84fc-81cb8cd67f4a)