Adds discovered/found repos to local path map
gitkraken/vscode-gitlens pull request #3633
Opened 2024-09-30 18:20 UTC by axosoft-ramint

Closes #3555

2024-09-30 18:22 UTC, axosoft-ramint commented on src/git/gitProviderService.ts
> +				}
@eamodio What are your thoughts on me putting this logic in its own function and just using `queueMicrotask` for it here and in the other place below?

2024-09-30 18:26 UTC, axosoft-ramint commented on src/git/gitProviderService.ts
> +				}
Ended up doing it, and added gating: https://github.com/gitkraken/vscode-gitlens/pull/3633/commits/7130c687ca4c996a609dfa59c39d7772c392ad49

2024-09-30 19:14 UTC, eamodio requested changes
Looks good -- minor tweaks requested

2024-09-30 19:14 UTC, eamodio commented on src/git/gitProviderService.ts
> +				);
Can we hide the need to call `getRepositoryIdentity` into the `addFoundRepositoryToMap` call, or at least allow it, but have that method do it if missing.

2024-09-30 19:14 UTC, eamodio commented on src/plus/repos/repositoryIdentityService.ts
> +			initialCommitSha: await this.container.git.getFirstCommitSha(repository.uri),
Please execute these 2 in parallel

2024-09-30 21:42 UTC, axosoft-ramint commented
@eamodio Improvements you mentioned are in. Ready to review again when you're able. Thanks!

2024-10-01 19:50 UTC, eamodio approved these changes
Added some tweaks (which can be squashed). So, if it looks good to you, it's ready to go.

2024-10-01 20:13 UTC, merged