Adds go to home view button to the commit graph title section
gitkraken/vscode-gitlens pull request #3877
Opened 2024-12-17 06:52 UTC by nzaytsev

# Description

![Screenshot 2024-12-23 at 16 07 01](https://github.com/user-attachments/assets/e773e9d0-ac31-4614-b1f6-6111048b16cc)

# Checklist

- [x] I have followed the guidelines in the Contributing document
- [x] My changes follow the coding style of this project
- [x] My changes build without any errors or warnings
- [x] My changes have been formatted and linted
- [x] My changes include any required corresponding changes to the documentation (including CHANGELOG.md and README.md)
- [x] My changes have been rebased and squashed to the minimal number (typically 1) of relevant commits
- [x] My changes have a descriptive commit message with a short title, including a `Fixes $XXX -` or `Closes #XXX -` prefix to auto-close the issue that your PR addresses

2024-12-17 21:01 UTC, eamodio commented
Pending question here: https://github.com/gitkraken/vscode-gitlens/issues/3873#issuecomment-2549620966

2024-12-20 19:38 UTC, eamodio requested changes
Please move the button to the right of the Launchpad button

2024-12-20 19:38 UTC, eamodio commented on src/webviews/apps/plus/graph/GraphWrapper.tsx
> +							<span slot="content">Open GitLens Home View</span>
```suggestion
							<span slot="content"><strong>GitLens Home</strong> —  track, manage, and collaborate on your branches and pull requests, all in one intuitive hub</span>
```

2024-12-23 11:47 UTC, sergeibbb approved these changes

2024-12-23 11:50 UTC, merged